name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Check conan version
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          conan --version
      - name: Configure
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          ./configure.sh
