name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
           pwd
           echo "/home/runner/.local/bin" >> $GITHUB_PATH
           ls /home/runner/.local/bin/
           pip3 install wheel setuptools
           pip3 install conan
           conan --version
    - name: configure
      run: sh ./configure.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
